name: Deploy Datasette and keep a history of changes of the partner db

on:
  push:
  schedule:
    - cron: "0 0 * * MON"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: datasette plugins
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: make publish
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Convert to newline-delimited JSON
        run: |-
          rm partners/* || true
          sqlite-diffable dump partners.db partners --all
      - name: Commit any changes
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add partners
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
