name: Deploy Datasette and keep a history of changes of the partner db

on:
  push:
    paths-ignore:
      - '.github/workflows/history.yml'
      - 'plot/**'
      - '*.md'
  schedule:
    - cron: "0 0 * * MON"

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          lfs: true
      - uses: astral-sh/setup-uv@v7
      - run: uv run datasette plugins
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: make publish
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Convert to newline-delimited JSON for archiving in git
        run: |-
          rm partners/* || true # remove old dump
          uv run sqlite-diffable dump partners.db partners --all
      - name: Commit any changes
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add partners
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
