name: Compute history

# History of Premier partners
# https://partners.amazonaws.com/partners/001E000000Ufa9FIAR/Thoughtworks

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: datasette plugins
      - name: Compute history
        run: |-
          git log --pretty=format:"%ad %H" --date=short | while read -r date hash
          do
                echo $date $hash
                git checkout $hash -- partners/
                rm partners.db || true
                sqlite-diffable load partners.db partners
                sqlite3 -csv partners.db "select '${date}' AS 'date', launch_rank, literal_name, services_count, reference_count, aws_certifications_count from summary where current_program_status = 'Premier';" >> premier.csv
          done
