name: Compute history

# History of Premier partners
# https://partners.amazonaws.com/partners/001E000000Ufa9FIAR/Thoughtworks

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: datasette plugins
      - name: Compute history
        run: |-
          git log --pretty=format:"%ad %H" --date=short | while read -r date hash
          do
                echo $date $hash
                git checkout $hash -- partners/
                rm partners.db || true
                sqlite-diffable load partners.db partners
                sqlite3 -csv partners.db "select '${date}' AS 'date', literal_name, aws_certifications_count from partners where current_program_status = 'Premier' and customer_type = 'Consulting Partner';" >> premier.csv
          done
          head premier.csv
          wc -l premier.csv
