name: AWS certifications page

# History of Premier partners
# https://partners.amazonaws.com/partners/001E000000Ufa9FIAR/Thoughtworks

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Deploy Datasette and keep a history of changes of the partner db"
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: astral-sh/setup-uv@v7
      - name: Compute history
        run: |-
          # Only process commits that contain data updates (match "Latest data:" pattern)
          git log --pretty=format:"%ad %H %s" --date=short | \
            awk '/Latest data:/ {print $1, $2}' | \
            while read -r date hash
          do
                echo "Processing: $date $hash"
                git checkout $hash -- partners/ || break
                # Only try LFS checkout if the file is actually tracked by LFS
                if git lfs ls-files -n | grep -q "partners/"; then
                  git lfs checkout partners/ 2>/dev/null || true
                fi
                rm partners.db || true
                uv run sqlite-diffable load partners.db partners
                sqlite3 -csv partners.db "select '${date}' AS 'date', literal_name, aws_certifications_count, customer_launches_count from partners where current_program_status = 'Premier' and customer_type = 'Consulting Partner';" >> premier.csv
          done
          wc -l premier.csv
          echo 'date,company,certifications,launches' | cat - premier.csv > temp && mv temp premier.csv
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - run: mkdir "_site" && mv plot/* premier.csv _site/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
