name: AWS certifications page

# History of Premier partners
# https://partners.amazonaws.com/partners/001E000000Ufa9FIAR/Thoughtworks

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Deploy Datasette and keep a history of changes of the partner db"
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - name: Compute history
        run: |-
          git log --pretty=format:"%ad %H" --date=short | while read -r date hash
          do
                echo $date $hash
                git checkout $hash -- partners/ || break
                rm partners.db || true
                sqlite-diffable load partners.db partners
                sqlite3 -csv partners.db "select '${date}' AS 'date', literal_name, aws_certifications_count from partners where current_program_status = 'Premier' and customer_type = 'Consulting Partner';" >> premier.csv
          done
          wc -l premier.csv
          echo 'date,company,certificates' | cat - premier.csv > temp && mv temp premier.csv
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - run:  mkdir "_site" && mv plot/* premier.csv _site/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4